/**
 * Created by User on 27.05.2015.
 */
function forecasts(forType, zodiac)
{
    if (forType == 'common') return 'Day calm but uneasy. Accuracy in some things is adjacent to the negligence of others. Sharpen "fad" and "troubles", funny and bad habits. Welcome painstaking and meticulous, but do not peretruzhdaetsya, it is not the best time for deeds. It is not necessary to show aggression to impose someone their understanding of events. The choice of activities can be guided by intuition. Business and literary texts, any current job better save to drafts - may come ideas about minor amendments to individual articles. Appropriate exercises associated with cleaning, cleaning, polishing details. It is useful to do health. The best prevention of diseases - twice the care of hygiene.';
    else
    {
        if (zodiac == 'Oven') return 'Oven\nThe day is not suitable for initiatives. Unable to dramatically expand the event in a new direction, but you can prepare for this stage - for example, put an end to the previous block of tasks. Against the general background of boredom and tranquility many Aries can separate "disturbances in the atmosphere." You can overreact to random events, or minor factors, which at another time would not attract your attention. Do not attach special importance of these moments, youll soon forget about them, and life will flow in the same way.';
        else if (zodiac == 'Telec') return 'The day is not suitable for initiatives. Unable to dramatically expand the event in a new direction, but you can prepare for this stage - for example, put an end to the previous block of tasks. Against the general background of boredom and tranquility many Aries can separate "disturbances in the atmosphere." You can overreact to random events, or minor factors, which at another time would not attract your attention. Do not attach special importance of these moments, youll soon forget about them, and life will flow in the same way.';
        else if (zodiac == 'Blizneci') return 'Stars give the Twins a green light, but sometimes are advised to use the stop sign. Be meticulous when it comes to accuracy, security, your reputation. If in doubt, do not limit guesses ask, learn, compare. The day is favorable for all those engaged in literary work, the collection and dissemination of information is related to education, sports, advertising and transport. Suitable day for participation in the training, the qualifying competition, the chance to win big.';
        else if (zodiac == 'Rak') return 'The situation has to be active and dynamic. If you want to succeed, dreams prefer concrete action. Today, in the foreground business information and useful contacts without intensive contacts with the outside world, you too will advance. Even the creative people will have to do business matters, for example, to register with the agency to apply for the contest, contact with potential benefactors. A good day to study. Cancers, employees should be given to current correspondence.';
        else if (zodiac == 'Lev') return 'That day, many Lions hold the wheel or on the phone, or in close contact with lots of people. Moment successful for any action related to campaigning, education, persuasion anyone. Your energy and eloquence will not leave anyone indifferent, and experience will help to choose the arguments that find their way to other peoples consciousness. You will not be difficult to fill the base of potential customers or attract the interesting person, as well as weed out those who do not fit your criteria.';
        else if (zodiac == 'Deva') return 'Virgos need now targeted contacts, so avoid idle chatter. Do not miss the chance to revive old contacts useful to you in one way or another. A great day for the meeting, the conversation with the boss, preliminary or re-interview. The ability to enhance their professional skills will be at Dev, whose work involves counseling, teaching, programming, coordinating foreign action, error checking. Before buying advice will not prevent the seller or user review.';
        else if (zodiac == 'Vesi') return 'Your intellectual capacity now at the height shortage of ideas will not. Youll also feel good physically and emotionally, so its easy to carry the load, quickly adapt to the new (or forgotten) environments. A beautiful day for Libra, who are studying, traveling, teaching, related to the research, publishing, education, political activities. It increases your chance to get an interesting offer, or an invitation from a distant region.';
        else if (zodiac == 'Skorpion') return 'This day will help satisfy the curiosity of Scorpios, and simultaneously increase the level of professional or amateur expertise. To do this, become the open system, both configured to receive and impact information. In the interests of the field track news and trends, study "inputs and outputs". Do not be afraid of critical situations, good fortune will help to get out of any scrape. It may decide to issue associated with learning, repairs, cooperation, travel, the purchase of equipment or means of communication.';
        else if (zodiac == 'Strelec') return 'A great day for any form of dialogue (consultation, discussion). Your interlocutors may be old friends, partners, customers, students. Other things being equal, they prefer the company now faces the recent acquaintances. We divorced Streltsov may intensify contacts with the same partner for marriage. Return is possible for various reasons, from parenting to business cooperation and the resumption of relations. Do not jump to conclusions, the coming days will show how such a promising comeback.';
        else if (zodiac == 'Kozerog') return 'Capricorn waiting for information-intensive and troublesome day. Be ready to support the right connections, give or arrange help more than usual to work with visitors, correspondence, sources, and quickly fill gaps in professional knowledge "on the job". You will have no problem if you know how to get along with colleagues, clientele, employees of institutions. Be open to contacts with authorities, especially if in the future apply for a higher position.';
        else if (zodiac == 'Vodoley') return 'A wonderful day for the exchange of ideas, deals, invitations, conferences, interviews and other forms of communications. Mobility will have time to make the day a lot of things. Many Aquarians attract communication in network. If you do not treat regulars virtual space, today suddenly can spend many hours in it. "Magnet", which you will draw, can become a conversation with an old friend, some pleasant memories. You may restore the old account, or change the nickname.';
        else if (zodiac == 'Ribi') return 'No time for idle curiosity. For most fish the timely receipt of information will become a necessity. No less important is the time to apply the necessary legal provisions, to connect to the case of competent intermediaries. If you are far from the boiling point of business life, you may need applied knowledge - for example, in connection with the repair or any household chores. Questions on the property and citizenship is better dealt with by lawyers. Find an old phone book, it can store the desired contacts.';
    }
}
module.exports = forecasts;